{% set name = "Magics" %}
{% set version = "4.5.0" %}

package:
  name: magics-metview-batch
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/3473464/{{ name }}-{{ version }}-Source.tar.gz
  sha256: d6f5682772ba7012f845b0c37f7bbaf5e12e6e9cf36da7524b234d8dc073ad2c

build:
  number: 0
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - boost-cpp
    - expat
    - glib
    - pango
    - cairo
    - proj
    - eccodes
    - libnetcdf
    - jinja2
    - zlib
  run:
    - expat
    - pango
    - cairo
    - proj
    - eccodes
    - simplejson
    - libnetcdf
    - zlib
  run_constrained:
    # magics-metview-batch is incompatible with magics-metview and magics
    - magics-metview ==9999999999
    - magics ==9999999999

test:
  commands:
    - printf "%s\n" "${MAGPLUS_HOME:?MAGPLUS_HOME is not set}"
    - test -f $PREFIX/lib64/libMagPlus${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib64/libMagPlusSingle${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib64/libMagPlusDouble${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib64/libMagPlus${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/lib64/libMagPlusSingle${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/lib64/libMagPlusDouble${SHLIB_EXT}  # [osx]

about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache-2.0
  license_file:
    - LICENSE_for_source_files
    - COPYING
    - LICENSE

  license_family: Apache
  summary: ECMWF's Meteorological plotting software with support for metview-batch.

extra:
  recipe-maintainers:
    - iainrussell
    - StephanSiemen
    - sylvielamythepaut
