{% set name = "Magics" %}
{% set version = "4.16.0" %}

package:
  name: magics-metview-batch
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/3473464/{{ name }}-{{ version }}-Source.tar.gz
  sha256: b5cf365e10e43abbb2e0b14db8e8d8db90486031f6c0de24b0b01c17a0197cf5

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - expat
    - glib
    - pango
    - xorg-xorgproto  # [not win]
    - cairo
    - proj
    - eccodes >=2.20.0
    - libnetcdf
    - zlib
    - openlibm  # [osx]
  run:
    - expat
    - pango
    - xorg-xorgproto  # [not win]
    - cairo
    - proj
    - eccodes >=2.20.0
    - simplejson
    - libnetcdf
    - zlib
    - openlibm  # [osx]

  run_constrained:
    # magics-metview-batch is incompatible with magics-metview and magics
    - magics-metview ==9999999999
    - magics ==9999999999

test:
  commands:
    - printf "%s\n" "${MAGPLUS_HOME:?MAGPLUS_HOME is not set}"
    - test -f $PREFIX/lib/libMagPlus${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libMagPlusSingle${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libMagPlusDouble${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libMagPlus${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/lib/libMagPlusSingle${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/lib/libMagPlusDouble${SHLIB_EXT}  # [osx]

about:
  home: https://confluence.ecmwf.int/display/MAGP/
  license: Apache-2.0
  license_file:
    - LICENSE_for_source_files
    - COPYING
    - LICENSE

  license_family: Apache
  summary: ECMWF's Meteorological plotting software with support for metview-batch.

extra:
  recipe-maintainers:
    - iainrussell
    - StephanSiemen
    - sylvielamythepaut
