{% set name = "Magics" %}
{% set version = "4.9.1" %}

package:
  name: magics-metview-batch
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/3473464/{{ name }}-{{ version }}-Source.tar.gz
  sha256: dd5ede7eef8296cd69323c181c5ae4a14444ef23c6d78002a203a5a5e05fb781

build:
  number: 2
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - expat
    - glib
    - pango
    - cairo
    - proj
    - eccodes >=2.20.0
    - libnetcdf
    - zlib
    - openlibm  # [osx]
  run:
    - expat
    - pango
    - cairo
    - proj
    - eccodes >=2.20.0
    - simplejson
    - libnetcdf
    - zlib
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    - openlibm  # [osx]

  run_constrained:
    # magics-metview-batch is incompatible with magics-metview and magics
    - magics-metview ==9999999999
    - magics ==9999999999

test:
  commands:
    - printf "%s\n" "${MAGPLUS_HOME:?MAGPLUS_HOME is not set}"
    - test -f $PREFIX/lib/libMagPlus${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libMagPlusSingle${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libMagPlusDouble${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libMagPlus${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/lib/libMagPlusSingle${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/lib/libMagPlusDouble${SHLIB_EXT}  # [osx]

about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache-2.0
  license_file:
    - LICENSE_for_source_files
    - COPYING
    - LICENSE

  license_family: Apache
  summary: ECMWF's Meteorological plotting software with support for metview-batch.

extra:
  recipe-maintainers:
    - iainrussell
    - StephanSiemen
    - sylvielamythepaut
